# Generated by Django 5.0.6 on 2024-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantDetails",
            fields=[
                (
                    "tenantid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("tenantname", models.TextField(unique=True)),
                (
                    "gender",
                    models.CharField(choices=[("F", "F"), ("M", "M")], max_length=1),
                ),
                ("permanentaddress", models.CharField(max_length=70)),
                ("occupation", models.TextField()),
                ("uid_number", models.CharField(max_length=10)),
                ("contactnumber", models.CharField(default="91", max_length=12)),
            ],
            options={
                "db_table": "private_data.tenant_details",
            },
        ),
    ]
