# Generated by Django 5.0.6 on 2024-07-04 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentDetails",
            fields=[
                (
                    "tenantid",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("contractstartdate", models.DateField(blank=True, null=True)),
                ("contractenddate", models.DateField(blank=True, null=True)),
                ("rent", models.IntegerField()),
                (
                    "flatno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "private_data.rent_details",
            },
        ),
        migrations.AddConstraint(
            model_name="rentdetails",
            constraint=models.CheckConstraint(
                check=models.Q(("contractstartdate__lt", models.F("contractenddate"))),
                name="rent_details_check",
            ),
        ),
    ]
